config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tracker.urls', namespace='tracker')),
]

tracker/urls.py
from django.conf.urls import url, include

from .views import *
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^users/$', UserListView.as_view(), name='users-list'),
    url(r'^users/(?P<pk>\d+)/$', UserDetailView.as_view(), name='user-detail'),
    url(r'^users/(?P<pk>\d+)/create$', UserCreateView.as_view(), name='user-create'),
    url(r'^users/(?P<pk>\d+)/update$', UserUpdateView.as_view(), name='user-update'),
    url(r'^users/(?P<pk>\d+)/delete$', UserDestroyView.as_view(), name='user-delete'),
    url(r'^tasks/$', TaskListView.as_view(), name='tasks-list'),
    url(r'^tasks/(?P<pk>\d+)/$', TaskDetailView.as_view(), name='task-detail'),
    url(r'^tasks/(?P<pk>\d+)/create$', TaskCreateView.as_view(), name='task-create'),
    url(r'^tasks/(?P<pk>\d+)/update$', TaskUpdateView.as_view(), name='task-update'),
    url(r'^tasks/(?P<pk>\d+)/delete$', TaskDestroyView.as_view(), name='task-delete'),
]

tracker/models/tasks.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Task(models.Model):

    name = models.CharField(
        max_length=100, verbose_name=_('Название задачи')
    )
    description = models.TextField(
        verbose_name=_('Описание')
    )
    user = models.ForeignKey(
        'tracker.User', null=True, blank=True,
        verbose_name=_('Назначенный пользователь')
    )
    checking_user = models.ForeignKey(
        'tracker.User', related_name='+',
        null=True, blank=True,
        verbose_name=_('Проверяющий пользователь')
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Задача')
        verbose_name_plural = _('Задачи')

tracker/models/users.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class User(models.Model):

    name = models.CharField(
        max_length=50, verbose_name=_('Имя')
    )
    position = models.CharField(
        max_length=50, verbose_name=_('Дожность')
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Пользователь')
        verbose_name_plural = _('Пользователи')

tracker/views.py
from django.shortcuts import render
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer
from django_filters.rest_framework import DjangoFilterBackend

from .serializers import UserSerializer, TaskSerializer
from .models.users import User
from .models.tasks import Task


class UserListView(generics.ListAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    serializer_class = UserSerializer
    template_name = 'tracker/users_list.html'

    def get(self, request, *args, **kwargs):
        queryset = User.objects.all()
        return Response({'users': queryset})


class UserDetailView(generics.RetrieveAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    serializer_class = UserSerializer
    template_name = 'tracker/user_detail.html'

    def get(self, request, pk):
        user = User.objects.get(pk=pk)
        tasks = Task.objects.filter(user=pk)
        return Response({'user': user, 'tasks': tasks})


class UserCreateView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserUpdateView(generics.UpdateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserDestroyView(generics.DestroyAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class TaskListView(generics.ListAPIView):
    serializer_class = TaskSerializer
    renderer_classes = [TemplateHTMLRenderer]
    filter_backends = (DjangoFilterBackend,)
    filter_fields = ('name',)
    search_fields = ('name',)
    template_name = 'tracker/tasks_list.html'

    def get(self, request, *args, **kwargs):
        queryset = Task.objects.all()[::-1]
        return Response({'tasks': queryset})


class TaskDetailView(generics.RetrieveAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    serializer_class = TaskSerializer
    template_name = 'tracker/task_detail.html'

    def get(self, request, pk):
        task = Task.objects.get(pk=pk)
        return Response({'task': task})


class TaskCreateView(generics.CreateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer


class TaskUpdateView(generics.UpdateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer


class TaskDestroyView(generics.DestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer


def index(request):
    return render(request, 'base.html')

templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="ru">

    {%  include 'blocks/head.html'  %}

    <body>

        {% include 'blocks/header.html' %}


        {% block content %}


        {% endblock %}

        {% include 'blocks/footer.html' %}


    </body>

</html>

templates/blocks/head.html
{% load staticfiles %}
{% load bootstrap3 %}

<head>
    <meta charset="UTF-8">
    <title>Трекер задач</title>

    <script src="{% bootstrap_jquery_url %}"></script>
    {% bootstrap_javascript %}
    {% bootstrap_css %}

</head>

templates/blocks/header.html
{% load staticfiles %}
{% load bootstrap3 %}

<header>

    <div class="menu">
        <ul class="nav nav-pills nav-justified navbar-inverse">
            <li id="users"><a href="{% url 'tracker:users-list' %}"><b>Пользователи</b></a></li>
            <li id="tasks"><a href="{% url 'tracker:tasks-list' %}"><b>Задачи</b></a></li>
        </ul>
    </div>

</header>

templates/tracker/task_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <ul class="nav nav-tabs">
                <li><a href="{% url 'tracker:tasks-list' %}">
                    <span class="glyphicon glyphicon-chevron-left"></span>Назад
                </a></li>
            </ul>
        </div>
        <div class="row">
                <div class="col-md-4">
                    <p><b>{{ task.name }}</b></p>
                </div>
                <div class="col-md-1">
                    <a href="{% url 'tracker:task-update' pk=user.id %}"><span class="glyphicon glyphicon-refresh"></span></a>
                    <a href="{% url 'tracker:task-delete' pk=user.id %}"><span class="glyphicon glyphicon-remove"></span></a>
                </div>
        </div>
        <div class="row">
            <p>{{ task.description }}</p>
        </div>
        <div class="row">
            {% if task.user %}
                <p>Исполняющий: {{ task.user }}</p>
            {% endif %}
            {% if task.checking_user %}
                <p>Проверяющий: {{ task.checking_user }}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/tracker/tasks_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            {% for task in tasks %}
            <a href="{% url 'tracker:task-detail' pk=task.id %}"><b>{{ task.name }}</b></a>
                {% if task.user %}
                    <p>На задачу назначен: {{ task.user }}</p>
                {% else %}
                    <p>На задачу никто не назначен</p>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/tracker/user_create_form.html
<div class="container-fluid">
    <div class="hidden-panel row" id="hidden-panel">
        <form id="city_form" data-url="{% url 'tracker:user-create' pk=user.id%}">
            <div class="col-xs-2">
                <span class="input-sm">Имя</span>
                <input type="text" class="form-control input-sm" id="name" name="name" value="">
            </div>
            <div class="col-xs-2">
                <span class="input-sm" >Дожность</span>
                <input type="text" class="form-control input-sm" id="position" name="position" value="">
            </div>
            <div class="col-xs-2">
                {% csrf_token %}
                <input type="button" id="create_user" class="btn btn-secondary btn-block" value="Добавить">
            </div>
        </form>
    </div>
</div>

templates/tracker/user_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <ul class="nav nav-tabs">
                <li><a href="{% url 'tracker:users-list' %}">
                    <span class="glyphicon glyphicon-chevron-left"></span>Назад
                </a></li>
            </ul>
        </div>
        <div class="row">
            <ul>
                <div class="col-md-4">
                    <p>{{ user.name }} ({{ user.position }})</p>
                </div>
                <div class="col-md-1">
                    <a href="{% url 'tracker:user-update' pk=user.id %}"><span class="glyphicon glyphicon-refresh"></span></a>
                    <a href="{% url 'tracker:user-delete' pk=user.id %}"><span class="glyphicon glyphicon-remove"></span></a>
                </div>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h5><b>Задачи:</b></h5>
                {% for task in tasks %}
                    <a href="{% url 'tracker:task-detail' pk=task.id %}">{{ task.name }}</a>
                    {% if task.checking_user %}
                        <p><small>Проверяющий: {{ task.checking_user }}</p>
                    {% endif %}
                {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}

templates/tracker/user_update_form.html
<div class="container-fluid">
    <div class="hidden-panel row" id="hidden-panel">
        <form id="city_form" data-url="{% url 'tracker:user-create' pk=user.id%}">
            <div class="col-xs-2">
                <span class="input-sm">Имя</span>
                <input type="text" class="form-control input-sm" id="name" name="name" value="">
            </div>
            <div class="col-xs-2">
                <span class="input-sm" >Дожность</span>
                <input type="text" class="form-control input-sm" id="position" name="position" value="">
            </div>
            <div class="col-xs-2">
                {% csrf_token %}
                <input type="button" id="create_user" class="btn btn-secondary btn-block" value="Добавить">
            </div>
        </form>
    </div>
</div>

templates/tracker/users_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <ul>
                {% for user in users %}
                    <div class="col-md-8">
                        <a href="{% url 'tracker:user-detail' pk=user.id %}">{{ user.name }} ({{ user.position }})</a>
                    </div>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}